### ISSUE TITLE
Crash on Android 8.1 devices

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#4] opened 2019-01-30 12:09 UTC
We are running some tests with netbare-sample. It is working fine on Android 7 and Android 9 devices that we have tested. However, on all Android 8.1 devices that we test, after turning on the VPN and browsing https pages using Chrome, the following crash occurs (100% reproducible on our devices):

2019-01-30 12:30:54.022 12391-12451/com.github.megatronking.netbare.sample E/NetBare: java.io.EOFException: Read error
    javax.net.ssl.SSLException: java.io.EOFException: Read error
        at com.android.org.conscrypt.SSLUtils.toSSLException(SSLUtils.java:295)
        at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1093)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:851)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:678)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:644)
        at com.github.megatronking.netbare.ssl.SSLCodec.engineUnwrap(SSLCodec.java:368)
        at com.github.megatronking.netbare.ssl.SSLCodec.unwrap(SSLCodec.java:303)
        at com.github.megatronking.netbare.ssl.SSLCodec.startDecode(SSLCodec.java:175)
        at com.github.megatronking.netbare.ssl.SSLCodec.decode(SSLCodec.java:166)
        at com.github.megatronking.netbare.ssl.SSLCodec.decode(SSLCodec.java:137)
        at com.github.megatronking.netbare.http.SSLHttpResponseCodec.decode(SSLHttpResponseCodec.java:70)
        at com.github.megatronking.netbare.http.SSLCodecInterceptor.decodeResponse(SSLCodecInterceptor.java:232)
        at com.github.megatronking.netbare.http.SSLCodecInterceptor.intercept(SSLCodecInterceptor.java:152)
        at com.github.megatronking.netbare.http.HttpIndexInterceptor.intercept(HttpIndexInterceptor.java:71)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:55)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:32)
        at com.github.megatronking.netbare.gateway.InterceptorChain.process(InterceptorChain.java:95)
        at com.github.megatronking.netbare.http.HttpSniffInterceptor.intercept(HttpSniffInterceptor.java:71)
        at com.github.megatronking.netbare.http.HttpIndexInterceptor.intercept(HttpIndexInterceptor.java:71)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:55)
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:32)
        at com.github.megatronking.netbare.gateway.InterceptorChain.process(InterceptorChain.java:95)
        at com.github.megatronking.netbare.http.HttpVirtualGateway.onSpecResponse(HttpVirtualGateway.java:117)
        at com.github.megatronking.netbare.gateway.SpecVirtualGateway.sendResponse(SpecVirtualGateway.java:78)
        at com.github.megatronking.netbare.NetBareVirtualGateway.sendResponse(NetBareVirtualGateway.java:102)
        at com.github.megatronking.netbare.tunnel.TcpVATunnel$2.onRead(TcpVATunnel.java:134)
        at com.github.megatronking.netbare.tunnel.NioTunnel.onRead(NioTunnel.java:101)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.process(TcpProxyServer.java:137)
        at com.github.megatronking.netbare.proxy.BaseProxyServer.run(BaseProxyServer.java:62)
        at com.github.megatronking.netbare.proxy.TcpProxyServer.run(TcpProxyServer.java:106)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.EOFException: Read error
        at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
        at com.android.org.conscrypt.SslWrapper.readDirectByteBuffer(SslWrapper.java:492)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1052)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1072)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1044)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:805)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:678) 
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:644) 
        at com.github.megatronking.netbare.ssl.SSLCodec.engineUnwrap(SSLCodec.java:368) 
        at com.github.megatronking.netbare.ssl.SSLCodec.unwrap(SSLCodec.java:303) 
        at com.github.megatronking.netbare.ssl.SSLCodec.startDecode(SSLCodec.java:175) 
        at com.github.megatronking.netbare.ssl.SSLCodec.decode(SSLCodec.java:166) 
        at com.github.megatronking.netbare.ssl.SSLCodec.decode(SSLCodec.java:137) 
        at com.github.megatronking.netbare.http.SSLHttpResponseCodec.decode(SSLHttpResponseCodec.java:70) 
        at com.github.megatronking.netbare.http.SSLCodecInterceptor.decodeResponse(SSLCodecInterceptor.java:232) 
        at com.github.megatronking.netbare.http.SSLCodecInterceptor.intercept(SSLCodecInterceptor.java:152) 
        at com.github.megatronking.netbare.http.HttpIndexInterceptor.intercept(HttpIndexInterceptor.java:71) 
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:55) 
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:32) 
        at com.github.megatronking.netbare.gateway.InterceptorChain.process(InterceptorChain.java:95) 
        at com.github.megatronking.netbare.http.HttpSniffInterceptor.intercept(HttpSniffInterceptor.java:71) 
        at com.github.megatronking.netbare.http.HttpIndexInterceptor.intercept(HttpIndexInterceptor.java:71) 
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:55) 
        at com.github.megatronking.netbare.http.HttpResponseChain.processNext(HttpResponseChain.java:32) 
        at com.github.megatronking.netbare.gateway.InterceptorChain.process(InterceptorChain.java:95) 
        at com.github.megatronking.netbare.http.HttpVirtualGateway.onSpecResponse(HttpVirtualGateway.java:117) 
        at com.github.megatronking.netbare.gateway.SpecVirtualGateway.sendResponse(SpecVirtualGateway.java:78) 
        at com.github.megatronking.netbare.NetBareVirtualGateway.sendResponse(NetBareVirtualGateway.java:102) 
        at com.github.megatronking.netbare.tunnel.TcpVATunnel$2.onRead(TcpVATunnel.java:134) 
        at com.github.megatronking.netbare.tunnel.NioTunnel.onRead(NioTunnel.java:101) 
        at com.github.megatronking.netbare.proxy.TcpProxyServer.process(TcpProxyServer.java:137) 
        at com.github.megatronking.netbare.proxy.BaseProxyServer.run(BaseProxyServer.java:62) 
        at com.github.megatronking.netbare.proxy.TcpProxyServer.run(TcpProxyServer.java:106) 
        at java.lang.Thread.run(Thread.java:764) 

Looks like there is a problem with ConscryptEngine on Android 8.1 devices that causes this error. 

Can anyone reproduce this on an Android 8.1 device?

**Comment by MegatronKing** [comment] 2019-01-30 14:48
Hi Wilos, thanks for your feedback. I found a related explanation from https://github.com/koush/AndroidAsync/issues/594#issuecomment-389508543. 

I'll fix this issue ASAP.

**Comment by MegatronKing** [comment] 2019-01-30 15:26
Hi Wilos, could you please try 8.1.0 again?

**Comment by MegatronKing** [comment] 2019-01-31 06:59
I installed a 8.1 emulator and reproduced this issue. After analysis, I found that the error is not from the HTTPS protocol, but other protocols. So the root cause is that some non-Http protocols were incorrectly processed by NetBare. I will do something to ignore those protocols.

Besides, there are some other issues on Android 8.1, such as ALPN, some work to be done.

**Comment by wilos** [comment] 2019-01-31 21:59
Thanks for the quick fix! I did some tests on an 8.1 device with your latest changes and I can confirm that it is now working well on 8.1 (SDK 27) devices, great! 

I did however find some other (unrelated) issues. I'll report them in new issues.

**Comment by MegatronKing** [comment] 2019-02-01 01:03
That's great! Thanks very much! I close this issue now.

**Closed by MegatronKing** 2019-02-01 01:03 UTC
Labels: bug
